# Generated by Django 2.1.5 on 2019-02-05 10:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=300)),
                ('progress', models.CharField(default='to do', max_length=100)),
                ('created_at', models.DateTimeField(blank='True', default=datetime.datetime.now)),
            ],
        ),
    ]
