# Generated by Django 2.1.5 on 2019-02-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20190205_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='progress',
            field=models.CharField(default='to do', max_length=100),
        ),
    ]
