# Generated by Django 2.1.5 on 2019-02-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20190205_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='progress',
            field=models.TextField(blank='True', default='to do'),
        ),
    ]
