# Generated by Django 2.1.5 on 2019-02-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_remove_task_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='progress',
            field=models.TextField(blank='True', default='to do'),
        ),
    ]
