# Generated by Django 2.1.5 on 2019-02-05 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20190205_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(default='low', max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='progress',
            field=models.CharField(default='to do', max_length=100),
        ),
    ]
